### ISSUE TITLE
デバッグモードで取得する投稿ID部分のロジック変更

### ISSUE THREAD

**Issue by gatespace** [megumiteam/simple-ga-ranking#16]
https://github.com/megumiteam/simple-ga-ranking/blob/master/simple-ga-ranking.php#L56-L60

WP Query の fields パラメータ使って 投稿IDの配列取得するようにする
（最終的に $arg で指定した投稿タイプやカテゴリー指定を生かしたい）

**Comment by wokamoto** [comment]
filter hook を使ってダミーデータを好きなように変更することができるようにしました。
https://github.com/megumiteam/simple-ga-ranking/blob/master/lib/functions.php#L98

フィルターフックの使い方は、こんな感じです。

```
<?php
add_filter( 'sga_ranking_dummy_data', function ( $ids, $args, $options ){
    return $ids;
}, 10, 3 );
```

**Comment by wokamoto** [comment]
このフィルターフックは ver.2.1.3. 以降で使用可能です。
