### ISSUE TITLE
Fatal error occurred under PHP8 environment

### ISSUE THREAD

**Issue by mypacecreator** [megumiteam/simple-ga-ranking#24]
PHP8.0.4環境下で以下のPHP Fatal errorが発生します。

> PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /wp-content/plugins/simple-ga-ranking/vendor/google/apiclient/src/Google/Utils.php on line 65

google-api-php-client のバージョンが古いのが原因のようです。
（hametuha/gapiwpの方で手を入れてもらわないといけない気もするのでまずは報告のみ）

**Comment by ash-r1** [comment]
PHP 7.4 では同様の箇所で Deprecated warnning が発生するようです。

```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/web/app/plugins/simple-ga-ranking/vendor/google/apiclient/src/Google/Utils.php on line 65

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /app/web/app/plugins/simple-ga-ranking/vendor/google/apiclient/src/Google/Http/REST.php on line 173
```

メンテされてない感じですかね。 forkするしかないのかなぁ。

**Comment by mt8** [comment]
こちらで対応中です

https://github.com/megumiteam/simple-ga-ranking/pull/25

**Comment by wokamoto** [comment]
修正した 3.0.0 をローンチ済みです。
