### ISSUE TITLE
About current implementation / 実装確認

### ISSUE THREAD

**Issue by pierrehenri220** [megumiteam/simple-ga-ranking#5]
Good day / みんなさん、こんにちわ！

For performance reason I'm trying to replace a weekly views popular post by simple ga ranking.
パーフォマンスの関係で一週間の人気記事リストをSimple GA Rankingに切り替えてみました：
Before / 修正前：
$weekly_posts = get_posts( array(
    'post_type'        => 'post',
    'posts_per_page'   => 10,
    'orderby'          => 'views',
    'order_range'      => 'weekly',
    'suppress_filters' => false
) );

After  / 修正後：
$args = array(
    'display_count' => 10,
    'period'        => 7,
    'post_type'     => 'post'
);
$weekly_posts = sga_ranking_get_date($args);

The point is, it looks like the plugin is getting the ranking from all the posts during the past 7 days.
I'm trying to the retrieve the ranking from the post only published during the last 7 days.
Do I understand it right ? Is there are any additional required ?

I would appreciate any help please :-) 
Pierre-Henri

テストしたところでは一週間で全体の記事から人気記事が表示されますので
（一年前公開した記事が表示されますとか、、、）
やりたいことは一週間公開した記事の中に人気記事が表示されるように。
あってますか？特別な設定（Filter）が必要ですか？ 

ヒント頂戴！お願いしますぅぅぅぅぅぅ〜
ピエール

**Comment by horike37** [comment]
こんにちは！ @grenouille220さん！
Sorry for the delay response :sweat_smile: 

>Do I understand it right ? 

Yup. You are right!
The `period` attribute allows you to get the ranking during the past some days what you want.

**Comment by docodoor-pierre** [comment]
@horike37 
Thank you very much for the answer and sorry for my late reply.
Actually this is a bit different from what I'm trying to accomplish.

I'm trying to get the ranking from the  **post published the last 7 days**,
for example the posts published between November 20th ( today ) and November 13th.

On my local wordpress, I setup the plugin but it looks like the plugin is using the analytics 
to get the ranking from **all the blog posts during the last 7 days**,
so older popular posts from last year are sometimes showing up too.

Is there a filter or something i can do to include / exclude the range of posts ?

Any help would be greatly appreciated. :-)

(By the way I'm french actually, I hope my english is understandable >< )
