### ISSUE TITLE
Function create_function() is deprecated in simple-ga-ranking.php on line 275

### ISSUE THREAD

**Issue by takamu** [megumiteam/simple-ga-ranking#6]
create_function()はPHP v7.2以降で非推奨となりましたので、コード書き換えて頂けますと幸いでございます！

**Comment by waviaei** [comment]
@horike37 Pull request #7 is for this issue. Thanks!

**Comment by horike37** [comment]
ういーっす。あざっす！レビューして新しいの公開します。

**Comment by horike37** [comment]
https://ja.wordpress.org/plugins/simple-ga-ranking/
対応版リリースしました！

**Comment by waviaei** [comment]
あざっす！
